//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schoole_Students
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASSROOMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLASSROOMS()
        {
            this.STUDENTS = new HashSet<STUDENTS>();
            this.SUBJECTS = new HashSet<SUBJECTS>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> MAXCAPACITY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENTS> STUDENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBJECTS> SUBJECTS { get; set; }
    }
}
