//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schoole_Students
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADS
    {
        public int SUBJECT_ID { get; set; }
        public int STUDENT_ID { get; set; }
        public int VALUE { get; set; }
    
        public virtual STUDENTS STUDENTS { get; set; }
        public virtual SUBJECTS SUBJECTS { get; set; }
    }
}
