//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schoole_Students
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchooleDBContext : DbContext
    {
        public SchooleDBContext()
            : base("name=SchooleDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLASSROOMS> CLASSROOMS { get; set; }
        public virtual DbSet<GRADS> GRADS { get; set; }
        public virtual DbSet<STUDENTS> STUDENTS { get; set; }
        public virtual DbSet<SUBJECTS> SUBJECTS { get; set; }
        public virtual DbSet<Table> Table { get; set; }
    }
}
