//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schoole_Students
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENTS()
        {
            this.GRADS = new HashSet<GRADS>();
        }
    
        public int Id { get; set; }
        public string NAME { get; set; }
        public string EMAILE { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public byte[] PHOTO { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> BIRTH { get; set; }
        public int CLASS_ID { get; set; }
    
        public virtual CLASSROOMS CLASSROOMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRADS> GRADS { get; set; }
    }
}
